- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python3-yoga-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-functional
        - ovsdbapp-neutron-ovn-tempest-ovs-release
    gate:
      jobs:
        - openstack-tox-functional
        - ovsdbapp-neutron-ovn-tempest-ovs-release
